# Generated by Django 4.2.4 on 2023-10-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appboots', '0002_familiar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fechaNacimiento',
        ),
    ]
