# Generated by Django 4.2.4 on 2023-10-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appboots', '0003_remove_familiar_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='sexo',
        ),
    ]
